#!/bin/bash

#--------Author: AHMAD SAMI -----------------

DATE=$(date "+%Y-%m-%d %H:%M:")
RAM_USAGE_FLOAT=$(free | awk '/Mem/{printf("RAM Usage: %.2f\n"), $3/$2*100}'| awk '{print $3}')
#SERVER_IP=$(hostname  -I | cut -f1 -d' ')
SERVER_IP=$(curl -s http://checkip.amazonaws.com)
CPU_USAGE_FLOAT=$(sar -P ALL 1 2 |grep 'Average.*all' |awk -F" " '{print 100.0 -$NF}')
RAM_USAGE_INT=$( printf "%.0f" $RAM_USAGE_FLOAT )
CPU_USAGE_INT=$( printf "%.0f" $CPU_USAGE_FLOAT )
FLAG_FILE="/tmp/flag_file_autogenerated"

if [[ ( -f "$FLAG_FILE" && "$RAM_USAGE_INT" -le 85 )  &&  ( -f "$FLAG_FILE" && "$CPU_USAGE_INT" -le 70 ) ]]; then

object_right='{"attachments": [{"color": "#2eb886", "title": "SERVER HEALTH IS HEALTHY","text": "'"date: $DATE UTC\n"' '"ram_used: $RAM_USAGE_FLOAT %\n"' '"server_ip: $SERVER_IP\n"' '"cpu_used: $CPU_USAGE_FLOAT %"'" }], "icon_emoji": "thumbsup" }'

rm $FLAG_FILE

curl -X POST -H 'Content-type: application/json' --data "$object_right" https://hooks.slack.com/services/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

exit

fi

if [[ ( ! -f "$FLAG_FILE" && "$RAM_USAGE_INT" -ge 85 )  ||  ( ! -f "$FLAG_FILE" && "$CPU_USAGE_INT" -ge 70 ) ]]; then

object_wrong='{"attachments": [{"color": "#fc0600", "title": "SERVER HEALTH IS PROBLEMATIC","text": "'"date: $DATE UTC\n"' '"ram_used: $RAM_USAGE_FLOAT %\n"' '"server_ip: $SERVER_IP\n"' '"cpu_used: $CPU_USAGE_FLOAT %"'" }], "icon_emoji": "warning"}'



[ -d /home/master/slack-integ-data/ ] ||  mkdir /home/master/slack-integ-data/
touch /home/master/slack-integ-data/top_proccesses_consuming_memory.txt
ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head > /home/master/slack-integ-data/top_proccesses_consuming_memory.txt

touch $FLAG_FILE

curl -X POST -H 'Content-type: application/json' --data "$object_wrong" https://hooks.slack.com/services/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

exit
fi
